
import "./globals.css";
import Navbar from "./components/Navbar";
import Head from "next/head";


import { StateProvider } from "./data/Context";
import { Footer } from "./components/Footer";

import {AuthProvider} from './AuthProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProvider>
        <StateProvider>
        <body className={`antialiased`}>
          
          <Navbar />
          {children}
          <Footer />
        </body>
        </StateProvider>
      </AuthProvider>
    </html>
  );
}
